name: n8n
slug: n8n
url: https://n8n.io
description: Workflow automation
version: 1.70.1
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
icon: icon.png
logo: icon.png
apparmor: true
host_network: true
hassio_api: true
homeassistant_api: true
stdin: true
panel_icon: mdi:transit-connection-variant
panel_title: n8n
webui: '[PROTO:option_name]://[HOST]:[PORT:5678]/'
watchdog: '[PROTO:option_name]://[HOST]:[PORT:5678]'
map:
  - ssl
  - share:rw
  - media:rw
  - backup:rw
ports:
  5678/tcp: 5678
ports_description:
  5678/tcp: n8n Web interface
environment:
  TINI_SUBREAPER: 'true'
options:
  N8N_PROTOCOL: http
  N8N_LOG_LEVEL: info
  N8N_VERSION_NOTIFICATIONS_ENABLED: false
  N8N_SSL_CERT: /ssl/fullchain.pem
  N8N_SSL_KEY: /ssl/privkey.pem
  N8N_HIDE_USAGE_PAGE: true
schema:
  CREDENTIALS_DEFAULT_NAME: str?
  CREDENTIALS_OVERWRITE_DATA: str?
  CREDENTIALS_OVERWRITE_ENDPOINT: str?
  DB_LOGGING_ENABLED: bool?
  DB_LOGGING_MAX_EXECUTION_TIME: int?
  DB_LOGGING_OPTIONS: list(query|error|schema|warn|info|log)?
  DB_MYSQLDB_DATABASE: str?
  DB_MYSQLDB_HOST: str?
  DB_MYSQLDB_PASSWORD: str?
  DB_MYSQLDB_PORT: int?
  DB_MYSQLDB_USER: str?
  DB_POSTGRESDB_DATABASE: str?
  DB_POSTGRESDB_HOST: str?
  DB_POSTGRESDB_PASSWORD: str?
  DB_POSTGRESDB_PORT: int?
  DB_POSTGRESDB_SCHEMA: str?
  DB_POSTGRESDB_SSL_CA: str?
  DB_POSTGRESDB_SSL_CERT: str?
  DB_POSTGRESDB_SSL_KEY: str?
  DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED: bool?
  DB_POSTGRESDB_USER: str?
  DB_SQLITE_VACUUM_ON_STARTUP: bool?
  DB_TABLE_PREFIX: str?
  DB_TYPE: list(sqlite|postgresdb)?
  EXECUTIONS_DATA_MAX_AGE: int?
  EXECUTIONS_DATA_PRUNE: bool?
  EXECUTIONS_DATA_PRUNE_MAX_COUNT: int?
  EXECUTIONS_DATA_PRUNE_TIMEOUT: int?
  EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS: bool?
  EXECUTIONS_DATA_SAVE_ON_ERROR: list(all|none)?
  EXECUTIONS_DATA_SAVE_ON_PROGRESS: bool?
  EXECUTIONS_DATA_SAVE_ON_SUCCESS: list(all|none)?
  EXECUTIONS_MODE: list(regular|queue)?
  EXECUTIONS_PROCESS (deprecated): list(main|own)?
  EXECUTIONS_TIMEOUT: int?
  EXECUTIONS_TIMEOUT_MAX: int?
  EXTERNAL_HOOK_FILES: str?
  GENERIC_TIMEZONE: str?
  N8N_AUTH_EXCLUDE_ENDPOINTS: str?
  N8N_AVAILABLE_BINARY_DATA_MODES: str?
  N8N_BINARY_DATA_STORAGE_PATH: str?
  N8N_BINARY_DATA_TTL: int?
  N8N_BLOCK_ENV_ACCESS_IN_NODE: bool?
  N8N_COMMUNITY_PACKAGES_ENABLED: bool?
  N8N_CONFIG_FILES: str?
  N8N_CUSTOM_EXTENSIONS: str?
  N8N_DEFAULT_BINARY_DATA_MODE: str?
  N8N_DEFAULT_LOCALE: str?
  N8N_DIAGNOSTICS_CONFIG_BACKEND: str?
  N8N_DIAGNOSTICS_CONFIG_FRONTEND: str?
  N8N_DIAGNOSTICS_ENABLED: bool?
  N8N_DISABLE_PRODUCTION_MAIN_PROCESS: bool?
  N8N_DISABLE_UI: bool?
  N8N_EDITOR_BASE_URL: str?
  N8N_EMAIL_MODE: str?
  N8N_ENCRYPTION_KEY: str?
  N8N_ENDPOINT_REST: str?
  N8N_ENDPOINT_WEBHOOK: str?
  N8N_ENDPOINT_WEBHOOK_TEST: str?
  N8N_ENDPOINT_WEBHOOK_WAIT: str?
  N8N_EVENTBUS_CHECKUNSENTINTERVAL: int?
  N8N_EVENTBUS_LOGWRITER_KEEPLOGCOUNT: int?
  N8N_EVENTBUS_LOGWRITER_LOGBASENAME: str?
  N8N_EVENTBUS_LOGWRITER_MAXFILESIZEINKB: int?
  N8N_EVENTBUS_LOGWRITER_SYNCFILEACCESS: bool?
  N8N_HIDE_USAGE_PAGE: bool?
  N8N_HIRING_BANNER_ENABLED: bool?
  N8N_HOST: str?
  N8N_LICENSE_ACTIVATION_KEY: str?
  N8N_LICENSE_AUTO_RENEW_ENABLED: bool?
  N8N_LICENSE_AUTO_RENEW_OFFSET: int?
  N8N_LICENSE_SERVER_URL: str?
  N8N_LISTEN_ADDRESS: str?
  N8N_LOG_FILE_COUNT_MAX: int?
  N8N_LOG_FILE_LOCATION: str?
  N8N_LOG_FILE_SIZE_MAX: int?
  N8N_LOG_LEVEL: list(info|warn|error|verbose|debug)?
  N8N_LOG_OUTPUT: list(console|file)?
  N8N_METRICS: bool?
  N8N_METRICS_INCLUDE_API_ENDPOINTS: bool?
  N8N_METRICS_INCLUDE_API_METHOD_LABEL: bool?
  N8N_METRICS_INCLUDE_API_PATH_LABEL: bool?
  N8N_METRICS_INCLUDE_API_STATUS_CODE_LABEL: bool?
  N8N_METRICS_INCLUDE_CREDENTIAL_TYPE_LABEL: bool?
  N8N_METRICS_INCLUDE_DEFAULT_METRICS: bool?
  N8N_METRICS_INCLUDE_NODE_TYPE_LABEL: bool?
  N8N_METRICS_INCLUDE_WORKFLOW_ID_LABEL: bool?
  N8N_METRICS_PREFIX: str?
  N8N_ONBOARDING_FLOW_DISABLED: bool?
  N8N_PATH: str?
  N8N_PAYLOAD_SIZE_MAX: int?
  N8N_PERSISTED_BINARY_DATA_TTL: int?
  N8N_PERSONALIZATION_ENABLED: bool?
  N8N_PROTOCOL: list(http|https)?
  N8N_PUBLIC_API_SWAGGERUI_DISABLED: bool?
  N8N_PUSH_BACKEND: str?
  N8N_SECURE_COOKIE: bool?
  N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN: bool?
  N8N_SMTP_HOST: str?
  N8N_SMTP_PASS: str?
  N8N_SMTP_PORT: int?
  N8N_SMTP_SENDER: str?
  N8N_SMTP_SSL: bool?
  N8N_SMTP_USER: str?
  N8N_SSL_CERT: str?
  N8N_SSL_KEY: str?
  N8N_TEMPLATES_ENABLED: bool?
  N8N_TEMPLATES_HOST: str?
  N8N_UM_EMAIL_TEMPLATES_INVITE: str?
  N8N_UM_EMAIL_TEMPLATES_PWRESET: str?
  N8N_USER_FOLDER: str?
  N8N_USER_MANAGEMENT_JWT_SECRET: str?
  N8N_VERSION_NOTIFICATIONS_ENABLED: bool?
  N8N_VERSION_NOTIFICATIONS_ENDPOINT: str?
  N8N_VERSION_NOTIFICATIONS_INFO_URL: str?
  N8N_WORKFLOW_CALLER_POLICY_DEFAULT_OPTION: str?
  N8N_WORKFLOW_TAGS_DISABLED: bool?
  NODES_ERROR_TRIGGER_TYPE: str?
  NODES_EXCLUDE: str?
  NODES_INCLUDE: str?
  NODE_FUNCTION_ALLOW_BUILTIN: str?
  NODE_FUNCTION_ALLOW_EXTERNAL: str?
  QUEUE_BULL_PREFIX: str?
  QUEUE_BULL_REDIS_CLUSTER_NODES: str?
  QUEUE_BULL_REDIS_DB: int?
  QUEUE_BULL_REDIS_HOST: str?
  QUEUE_BULL_REDIS_PASSWORD: str?
  QUEUE_BULL_REDIS_PORT: int?
  QUEUE_BULL_REDIS_TIMEOUT_THRESHOLD: int?
  QUEUE_BULL_REDIS_USERNAME: str?
  QUEUE_HEALTH_CHECK_ACTIVE: bool?
  QUEUE_HEALTH_CHECK_PORT: int?
  QUEUE_RECOVERY_INTERVAL: int?
  QUEUE_WORKER_TIMEOUT: int?
  VUE_APP_URL_BASE_API: str?
  WEBHOOK_URL: str?
  WORKFLOWS_DEFAULT_NAME: str?
